### ISSUE TITLE
Event-Experience

### ISSUE THREAD

**Issue by ImNotStable** [Fusezion/skript-fishing#1]
### Description
Could you use [this](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerFishEvent.html#getExpToDrop()) and [this](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/player/PlayerFishEvent.html#setExpToDrop(int)) to create an event-experience. I'd like to edit the experience gained from fishing.

**Comment by Fusezion** [comment]
Hey sorry for not getting to this, I've decided to archive this addon as there's more reliable ones like [SkBee](https://github.com/Shanebeee/SkBee)
Additionally I didn't ever add a `event-experience` as there's a fishing experience syntax, additionally experience in skript is pretty bad and something that shouldn't be used until they add better conversions for numbers and such
